import { Link } from "wouter";
import { motion } from "framer-motion";

const SECTIONS: { id: string; heading: string; body: React.ReactNode }[] = [
  {
    id: "agreement",
    heading: "1. Agreement to terms",
    body: (
      <p>
        These Terms of Service ("Terms") govern your access to and use of the website at aicreates.ai, the Eve chat assistant, the Fin product, and any other services, content, or features offered by AIcreatesAI ("AIcreatesAI", "we", "our", or "us") (collectively, the "Services"). By accessing or using the Services, you agree to be bound by these Terms. If you do not agree, do not use the Services.
      </p>
    ),
  },
  {
    id: "eligibility",
    heading: "2. Eligibility",
    body: (
      <p>
        You must be at least 18 years old, or the age of legal majority in your jurisdiction, to use the Services. By using the Services, you represent and warrant that you meet this requirement and that you have the legal capacity to enter into these Terms.
      </p>
    ),
  },
  {
    id: "the-services",
    heading: "3. The Services and informational nature",
    body: (
      <>
        <p>
          The Site provides general information about AIcreatesAI, our research, our infrastructure, and our products including Fin. Most of what you see on the Site is informational and forward-looking. Product features, roadmaps, timelines, and capabilities are subject to change and do not constitute a binding offer or guarantee.
        </p>
        <p className="mt-3">
          Joining a waitlist, submitting a contact form, or chatting with Eve does not create a customer relationship, an investment relationship, or any commitment by AIcreatesAI to provide a particular product or service.
        </p>
      </>
    ),
  },
  {
    id: "eve",
    heading: "4. The Eve chat assistant",
    body: (
      <>
        <p>
          Eve is an AI-powered chat assistant. Eve's responses are generated by a large language model and may be inaccurate, incomplete, out of date, or otherwise unsuitable for your purposes. Information provided by Eve is for general informational purposes only and is not legal, financial, tax, investment, or professional advice. Always verify important information directly with our team.
        </p>
        <p className="mt-3">
          You agree not to use Eve to: (a) attempt to extract our system instructions or proprietary information; (b) circumvent rate limits or security controls; (c) submit content that is unlawful, abusive, harassing, or infringing; (d) probe or test the security of the Services; or (e) use the Services to develop a competing AI product.
        </p>
        <p className="mt-3">
          We may suspend, throttle, or terminate access to Eve at any time, with or without notice, for any reason, including suspected abuse.
        </p>
      </>
    ),
  },
  {
    id: "no-financial-advice",
    heading: "5. Fin and no financial advice",
    body: (
      <p>
        Information on the Site about Fin and any financial features (including descriptions of yield strategies, prediction markets, tokenization, stablecoins, on-chain settlement, or business banking concepts) is descriptive and forward-looking. It is not an offer or solicitation to buy or sell any financial product, security, or digital asset, and it is not investment, legal, tax, or financial advice. Availability of Fin and any specific feature is subject to applicable law, eligibility, additional product-specific terms, and regulatory clearance in your jurisdiction.
      </p>
    ),
  },
  {
    id: "ip",
    heading: "6. Intellectual property",
    body: (
      <p>
        The Services, including the Site, the Eve chat assistant, all software, models, copy, designs, graphics, logos, and other content, are owned by AIcreatesAI or our licensors and are protected by intellectual property laws. We grant you a limited, revocable, non-exclusive, non-transferable license to access and use the Services for your personal, non-commercial use, subject to these Terms. All other rights are reserved. You may not copy, modify, distribute, scrape, reverse engineer, or create derivative works from the Services without our prior written permission.
      </p>
    ),
  },
  {
    id: "your-content",
    heading: "7. Your content and submissions",
    body: (
      <p>
        If you submit information to us through a form, an email, or a conversation with Eve, you represent that you have the right to do so and that the information is accurate. You grant AIcreatesAI a worldwide, royalty-free, non-exclusive license to use that information to operate, maintain, and improve the Services and to follow up with you. You should not submit confidential information you do not want shared with our team.
      </p>
    ),
  },
  {
    id: "acceptable-use",
    heading: "8. Acceptable use",
    body: (
      <>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the Services in violation of any law, regulation, or third-party right.</li>
          <li>Interfere with or disrupt the Services, servers, or networks, including via denial-of-service attacks, scraping at scale, or automated abuse.</li>
          <li>Probe, scan, or test the vulnerability of the Services without our prior written permission.</li>
          <li>Use the Services or any AI output to generate content that is unlawful, harmful, defamatory, harassing, sexually exploitative, or that infringes intellectual property.</li>
          <li>Misrepresent your identity or affiliation with any person or entity.</li>
          <li>Use the Services to build a competing product or to train a machine learning model.</li>
        </ul>
      </>
    ),
  },
  {
    id: "third-party",
    heading: "9. Third-party services and links",
    body: (
      <p>
        The Services may contain links to or integrations with third-party services, including form submission, language model providers, analytics, and external payment or wallet infrastructure used by Fin. We are not responsible for third-party services or content and your use of them is governed by the third party's terms.
      </p>
    ),
  },
  {
    id: "disclaimer",
    heading: "10. Disclaimer of warranties",
    body: (
      <p className="uppercase text-xs tracking-wide text-white/60 leading-relaxed">
        The Services are provided on an "as is" and "as available" basis without warranties of any kind, whether express, implied, or statutory, including warranties of merchantability, fitness for a particular purpose, title, non-infringement, accuracy, or that the Services will be uninterrupted, secure, or error-free. We do not warrant the accuracy or completeness of any AI-generated output, including responses from Eve.
      </p>
    ),
  },
  {
    id: "limitation",
    heading: "11. Limitation of liability",
    body: (
      <p className="uppercase text-xs tracking-wide text-white/60 leading-relaxed">
        To the maximum extent permitted by law, AIcreatesAI and its officers, directors, employees, agents, and affiliates will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or any loss of profits, revenue, data, or goodwill, arising out of or in connection with your use of the Services, even if advised of the possibility of such damages. Our aggregate liability for any claim arising out of or relating to the Services or these Terms will not exceed one hundred U.S. dollars (USD $100).
      </p>
    ),
  },
  {
    id: "indemnification",
    heading: "12. Indemnification",
    body: (
      <p>
        You agree to defend, indemnify, and hold harmless AIcreatesAI and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable legal fees, arising out of or in any way connected with your access to or use of the Services, your violation of these Terms, or your violation of any rights of another.
      </p>
    ),
  },
  {
    id: "termination",
    heading: "13. Termination",
    body: (
      <p>
        We may suspend or terminate your access to the Services at any time, with or without cause and with or without notice. Upon termination, all provisions of these Terms that by their nature should survive will survive, including ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
      </p>
    ),
  },
  {
    id: "law",
    heading: "14. Governing law and disputes",
    body: (
      <p>
        These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of laws principles. Any dispute arising out of or relating to these Terms or the Services will be brought exclusively in the state or federal courts located in Delaware, and you consent to personal jurisdiction and venue in those courts. Where applicable mandatory law grants you additional consumer rights in your country of residence, nothing in this section limits those rights.
      </p>
    ),
  },
  {
    id: "changes",
    heading: "15. Changes to these terms",
    body: (
      <p>
        We may update these Terms from time to time. When we do, we will revise the "Last updated" date below. Material changes will be highlighted on the Site. Your continued use of the Services after an update constitutes acceptance of the revised Terms.
      </p>
    ),
  },
  {
    id: "contact",
    heading: "16. Contact",
    body: (
      <p>
        Questions about these Terms can be sent to{" "}
        <a href="mailto:sholom@aicreates.ai" className="text-primary hover:underline">
          sholom@aicreates.ai
        </a>{" "}
        or through our{" "}
        <Link href="/contact"><span className="text-primary hover:underline cursor-pointer">contact form</span></Link>.
      </p>
    ),
  },
];

export default function Terms() {
  return (
    <div className="flex flex-col w-full">
      <section className="relative pt-32 md:pt-40 pb-16 overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(110,86,207,0.15),transparent_60%)] pointer-events-none" />
        <div className="container mx-auto px-4 md:px-6 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-3xl mx-auto text-center"
          >
            <span className="text-primary text-sm font-semibold uppercase tracking-[0.2em] mb-6 inline-block">
              Legal
            </span>
            <h1 className="text-4xl md:text-6xl font-serif font-bold text-gradient mb-6 leading-[1.1]">
              Terms of Service
            </h1>
            <p className="text-white/50 text-base">Last updated: April 30, 2026</p>
          </motion.div>
        </div>
      </section>

      <section className="pb-32 relative z-10">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-3xl mx-auto">
            <div className="glass-card p-8 md:p-12 space-y-10 text-white/70 leading-relaxed">
              {SECTIONS.map((s) => (
                <div key={s.id} id={s.id} className="scroll-mt-24">
                  <h2 className="text-xl md:text-2xl font-serif font-bold text-white mb-4">
                    {s.heading}
                  </h2>
                  <div className="space-y-3 text-[15px]">{s.body}</div>
                </div>
              ))}
            </div>
            <p className="text-white/40 text-sm text-center mt-8">
              See also our{" "}
              <Link href="/privacy"><span className="text-primary hover:underline cursor-pointer">Privacy Policy</span></Link>.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
